name: Build APK

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # 1. Исправляем ошибку памяти
      - name: Fix gradle.properties (Memory)
        run: |
          sed -i '/MaxPermSize/d' gradle.properties
          echo "org.gradle.jvmargs=-Xmx4096m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8" >> gradle.properties

      # 2. Исправляем ошибку с Git (begin 1, end 0)
      # Мы просто заменяем вызов функции gitVersion... на жестко прописанные цифры
      - name: Fix build.gradle (Hardcode version)
        run: |
          sed -i 's/version_code = gitVersionCode()/version_code = 1/' build.gradle
          sed -i 's/version_name = gitVersionName()/version_name = "1.0.0-debug"/' build.gradle

      # 3. Создаем google-services.json
      - name: Create google-services.json
        run: |
          cat <<EOF > app/google-services.json
          {
            "project_info": {
              "project_number": "399896978162",
              "firebase_url": "https://studio-4143509276-85720-default-rtdb.firebaseio.com",
              "project_id": "studio-4143509276-85720",
              "storage_bucket": "studio-4143509276-85720.firebasestorage.app"
            },
            "client": [
              {
                "client_info": {
                  "mobilesdk_app_id": "1:399896978162:android:fc968b323d8d04a7c5666b",
                  "android_client_info": {
                    "package_name": "com.company.message"
                  }
                },
                "oauth_client": [],
                "api_key": [
                  {
                    "current_key": "AIzaSyDQqLTQgEZpS-UbqjWniGGaR8C15YNgQkI"
                  }
                ],
                "services": {
                  "appinvite_service": {
                    "other_platform_oauth_client": []
                  }
                }
              }
            ],
            "configuration_version": "1"
          }
          EOF

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Tindroid-Debug
          path: app/build/outputs/apk/debug/*.apk
          
